In [1]:
import pandas as pd
import numpy as np

E:\anaconda\lib\site-packages\pandas\core\computation\expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
# Load the Excel file into a pandas DataFrame
df = pd.read_csv('raw_data.csv')

In [3]:
df['click_bool']

0          0
1          0
2          0
3          0
4          0
          ..
9917525    0
9917526    1
9917527    0
9917528    0
9917529    0
Name: click_bool, Length: 9917530, dtype: int64

In [4]:
columns = ['srch_id', 'prop_id', 'prop_starrating', 'prop_review_score', 'prop_brand_bool', 'prop_location_score1', 'prop_location_score2', 'prop_log_historical_price', 'price_usd', 'promotion_flag', 'srch_length_of_stay', 'srch_adults_count', 'srch_children_count', 'srch_saturday_night_bool','srch_booking_window', 'booking_bool']

In [5]:
df_OR = df[columns]

In [6]:
df_OR

,srch_id,prop_id,prop_starrating,prop_review_score,prop_brand_bool,prop_location_score1,prop_location_score2,prop_log_historical_price,price_usd,promotion_flag,srch_length_of_stay,srch_adults_count,srch_children_count,srch_saturday_night_bool,srch_booking_window,booking_bool
0,1,893,3,3.5,1,2.83,0.0438,4.95,104.77,0,1,4,0,1,0,0
1,1,10404,4,4.0,1,2.20,0.0149,5.03,170.74,0,1,4,0,1,0,0
2,1,21315,3,4.5,1,2.20,0.0245,4.92,179.80,0,1,4,0,1,0,0
3,1,27348,2,4.0,1,2.83,0.0125,4.39,602.77,0,1,4,0,1,0,0
4,1,29604,4,3.5,1,2.64,0.1241,4.93,143.58,0,1,4,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9917525,665574,32019,4,3.5,0,2.48,0.0551,4.53,66.07,0,2,1,0,0,7,0
9917526,665574,33959,4,3.0,1,2.20,0.3344,4.39,67.10,0,2,1,0,0,7,1
9917527,665574,35240,4,0.0,0,1.79,NaN,4.64,73.91,0,2,1,0,0,7,0
9917528,665574,94437,4,0.0,0,2.94,0.0928,4.64,66.07,0,2,1,0,0,7,0
9917529,665574,99509,4,4.5,1,2.08,0.0344,4.64,82.06,0,2,1,0,0,7,0

In [7]:
df_OR=df_OR[df_OR['srch_length_of_stay']==1]

In [8]:
df_OR.reset_index(drop=True, inplace=True)

In [9]:
df_OR

,srch_id,prop_id,prop_starrating,prop_review_score,prop_brand_bool,prop_location_score1,prop_location_score2,prop_log_historical_price,price_usd,promotion_flag,srch_length_of_stay,srch_adults_count,srch_children_count,srch_saturday_night_bool,srch_booking_window,booking_bool
0,1,893,3,3.5,1,2.83,0.0438,4.95,104.77,0,1,4,0,1,0,0
1,1,10404,4,4.0,1,2.20,0.0149,5.03,170.74,0,1,4,0,1,0,0
2,1,21315,3,4.5,1,2.20,0.0245,4.92,179.80,0,1,4,0,1,0,0
3,1,27348,2,4.0,1,2.83,0.0125,4.39,602.77,0,1,4,0,1,0,0
4,1,29604,4,3.5,1,2.64,0.1241,4.93,143.58,0,1,4,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4289197,665573,117267,4,4.5,1,2.94,0.1153,5.91,259.00,1,1,2,2,0,3,0
4289198,665573,125075,4,4.5,1,3.09,0.0304,6.21,349.00,0,1,2,2,0,3,0
4289199,665573,127402,5,4.5,1,2.56,0.0483,6.21,429.00,0,1,2,2,0,3,0
4289200,665573,128251,3,4.0,1,3.33,0.0410,5.63,175.00,1,1,2,2,0,3,0
4289201,665573,135414,3,4.0,1,2.83,0.0651,5.80,218.00,1,1,2,2,0,3,0

In [ ]:
grouped = df_OR.groupby('srch_id')

# Check if any rows in each group have missing values in orig_destination_distance column
assortments_to_drop = []
for column in columns:
    for group_name, group_df in grouped:
            if group_df[column].isna().any():
                assortments_to_drop.append(group_name)
# Drop the assortments with missing values
df_OR = df_OR[~df_OR['srch_id'].isin(assortments_to_drop)]
df_OR

In [ ]:
df_OR.to_csv("df_OR_without_NAs_single_stay_night.csv",index=None)

In [ ]:
filter_columns = ['prop_starrating', 'prop_review_score', 'prop_location_score1', 'prop_location_score2', 
                  'prop_log_historical_price', 'price_usd', 'srch_adults_count', 'srch_children_count']
for column in filter_columns:
    lower_bound = np.sort(np.array(df_OR[column]))[int(0.005*len(df_OR))]
    upper_bound = np.sort(np.array(df_OR[column]))[int(0.995*len(df_OR))]

In [ ]:
df_OR = pd.read_csv('df_OR_without_NAs_single_stay_night.csv')

In [ ]:
grouped = df_OR.groupby('srch_id')
filter_columns = ['prop_starrating', 'prop_review_score', 'prop_location_score1', 'prop_location_score2', 
                  'prop_log_historical_price', 'price_usd', 'srch_adults_count', 'srch_children_count','srch_booking_window']
# Check if any rows in each group have missing values in orig_destination_distance column
assortments_to_drop = []
for column in filter_columns:
    lower_bound = np.sort(np.array(df_OR[column]))[int(0.005*len(df_OR))]
    upper_bound = np.sort(np.array(df_OR[column]))[int(0.995*len(df_OR))]
    for group_name, group_df in grouped:
            if sum((group_df[column] >= lower_bound) & (group_df[column] <= upper_bound)) != len(group_df):
                assortments_to_drop.append(group_name)
# Drop the assortments with missing values
df_OR = df_OR[~df_OR['srch_id'].isin(assortments_to_drop)]
df_OR

In [ ]:
df_OR['srch_booking_window'] = df_OR['srch_booking_window'].transform(lambda s: 1 if s>7 else 0)

In [ ]:
df_OR['prop_log_historical_price'] = np.exp(df_OR['prop_log_historical_price'])

In [ ]:
df_OR

In [ ]:
df_OR.reset_index(drop=True, inplace=True)

In [ ]:
if df_OR.isna().any().any():
    print("There are missing values in the DataFrame")
else:
    print("There are no missing values in the DataFrame")

In [ ]:
temp_df=df_OR.groupby('srch_id').agg({'booking_bool':np.size})
total_list = list(temp_df.index)
print(len(total_list))
print("maximum_size of the assortment is:",max(temp_df['booking_bool']))
max_num = max(temp_df['booking_bool'])

In [ ]:
for cat in cat_columns:
    temp_list = list(df_OR.groupby(cat).groups)
    temp_dic = {}
    for i in range(len(temp_list)):
        temp_dic[temp_list[i]] = i
    df_OR[cat] = df_OR[cat].transform(lambda s: temp_dic[s])
    print(cat, len(temp_list))

In [9]:
i = 0
trans_dict = {}
for item in sorted(df_OR['prop_review_score'].unique()):
    trans_dict[item] = i
    i += 1

In [11]:
df_OR['prop_review_score'] = df_OR['prop_review_score'].map(trans_dict)

In [12]:
df_OR.to_csv("df_OR_normal_process_with_nonpurchase_clean.csv",index=False)

,srch_id,prop_id,prop_starrating,prop_review_score,prop_brand_bool,prop_location_score1,prop_location_score2,prop_log_historical_price,price_usd,promotion_flag,srch_length_of_stay,srch_adults_count,srch_children_count,srch_saturday_night_bool,srch_booking_window,booking_bool
0,42,2068,2,7,1,1.61,0.1238,89.121446,68.77,0,1,2,0,1,1,0
1,42,14445,0,5,0,1.10,0.0457,141.174964,50.57,0,1,2,0,1,1,0
2,42,24416,2,0,0,0.69,0.0099,134.289780,79.89,0,1,2,0,1,1,0
3,42,27963,0,8,0,1.10,0.0573,141.174964,123.38,0,1,2,0,1,1,0
4,42,48834,2,6,0,0.69,0.0347,134.289780,70.79,0,1,2,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1233925,665550,82927,4,7,1,5.50,0.0776,317.348329,299.00,0,1,2,0,1,0,0
1233926,665550,98862,4,7,1,5.81,0.1515,424.113030,279.00,0,1,2,0,1,0,0
1233927,665550,126657,4,7,1,5.96,0.1966,419.893035,299.00,1,1,2,0,1,0,0
1233928,665550,131357,4,8,1,3.78,0.0240,372.411714,269.00,0,1,2,0,1,0,0
1233929,665550,139197,4,7,0,5.96,0.1651,343.779341,299.00,0,1,2,0,1,0,0